Repository grafeas/kritis, pull requests merged in 2020-07, with the labels that each got.

#557 Add UploadAttestationOccurrence() method in metadata client interface
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/metadata/metadata_test.go
  pkg/kritis/testutil/metadata_mock.go
Labels: size/L

#555 Improve logging for signer vulnerability check
  cmd/kritis/signer/main.go
  pkg/kritis/crd/vulnzsigningpolicy/vulnzsigningpolicy.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
Labels: size/S

#556 A function to create attestation payloads
  pkg/kritis/attestation/payload.go
  pkg/kritis/container/container.go
  pkg/kritis/util/util.go
Labels: size/M

#561 Rename KeyType to AuthenticatorType
  pkg/kritis/cryptolib/jwt_test.go
  pkg/kritis/cryptolib/public_key.go
  pkg/kritis/cryptolib/signature_algorithm.go
  pkg/kritis/cryptolib/verifier.go
  pkg/kritis/cryptolib/verifier_test.go
Labels: size/L

#558 Use cryptolib signer in kritis signer
  cmd/kritis/signer/main.go
  integration/signer/tests/test-bypass-and-sign.sh
  integration/signer/tests/test-check-and-sign-bad.sh
  integration/signer/tests/test-check-and-sign-good.sh
  pkg/kritis/signer/signer.go
Labels: size/L

#563 Fix signer command line flags
  cmd/kritis/signer/main.go
  integration/signer/signer_int.sh
Labels: size/S

#562 Move pkg/kritis/cryptolib to pkg/attestlib.
  cmd/kritis/signer/main.go
  pkg/attestlib/attestation.go
  pkg/attestlib/authenticated_attestation.go
  pkg/attestlib/authenticated_attestation_test.go
  pkg/attestlib/e2etest/pgp_e2e_test.go
  pkg/attestlib/jwt.go
  pkg/attestlib/jwt_test.go
  pkg/attestlib/pgp.go
  pkg/attestlib/pgp_test.go
  pkg/attestlib/public_key.go
  pkg/attestlib/signature_algorithm.go
  pkg/attestlib/signer.go
  pkg/attestlib/verifier.go
  pkg/attestlib/verifier_test.go
  pkg/kritis/attestation/payload.go
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/cache_test.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/metadata/metadata_test.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
  pkg/kritis/signer/cloud_kms.go
  pkg/kritis/signer/signer.go
  pkg/kritis/testutil/metadata_mock.go
  pkg/kritis/util/util.go
Labels: size/L

#559 Add Overview doc for Attestation Library
  pkg/attestlib/README.md
Labels: size/M

#540 Verify function for detached signatures
  pkg/attestlib/jwt.go
  pkg/attestlib/verify_detached.go
  pkg/attestlib/verify_detached_test.go
Labels: size/L

#568 Support passphrase-encrypted private keys in Crypto Library
  cmd/kritis/signer/main.go
  pkg/attestlib/e2etest/pgp_e2e_test.go
  pkg/attestlib/pgp.go
  pkg/attestlib/pgp_test.go
  pkg/kritis/util/util.go
Labels: size/L

#570 Implement pkix sign
  pkg/attestlib/ec_sign.go
  pkg/attestlib/ec_sign_test.go
  pkg/attestlib/pkix.go
  pkg/attestlib/pkix_key.go
  pkg/attestlib/pkix_key_test.go
  pkg/attestlib/pkix_test.go
  pkg/attestlib/rsa_sign.go
  pkg/attestlib/rsa_sign_test.go
  pkg/attestlib/signer.go
Labels: size/XL

#567 Add deployment integration in signer integration testing
  cmd/kritis/signer/main.go
  integration/signer/signer_int.sh
  integration/signer/tests/test-bypass-and-sign-with-kms.sh
  integration/signer/tests/test-bypass-and-sign.sh
  integration/signer/tests/test-check-and-sign-bad.sh
  integration/signer/tests/test-check-and-sign-good.sh
  integration/signer/tests/test-overwrite.sh
Labels: size/M

#554 Update new public key to use signatureAlgorithm field.
  pkg/attestlib/e2etest/pgp_e2e_test.go
  pkg/attestlib/public_key.go
  pkg/attestlib/signature_algorithm.go
  pkg/attestlib/verifier_test.go
  pkg/kritis/review/validating_transport.go
Labels: size/M

#578 Fix cloud build signer integration test
  integration/signer/signer_int.sh
  integration/signer/tests/test-bypass-and-sign-with-kms.sh
  integration/signer/tests/test-bypass-and-sign.sh
  integration/signer/tests/test-check-and-sign-good.sh
Labels: size/S
