Repository grafeas/kritis, pull requests merged in 2020-12, with the labels that each got.

#585 wait & timeout if no container analysis occurrence is found for the image
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
Labels: size/S

#600 Add go mod vendor in test.sh to fix module version mismatch
  hack/test.sh
Labels: size/XS

#599 Increase time limit on cloud build integration
  integration/signer/cloudbuild.yaml
Labels: size/XS

#601 Install gotestsum outside of kritis folder
  hack/test.sh
Labels: size/XS

#595 gcr kritis signer
  Makefile
  cmd/kritis/gcr-signer/.gitignore
  cmd/kritis/gcr-signer/api-specification.yaml
  cmd/kritis/gcr-signer/main.go
  cmd/kritis/gcr-signer/server.go
  deploy/gcr-kritis-signer/Dockerfile
  deploy/gcr-kritis-signer/cloudbuild.yaml
  docs/gcr-signer.md
  docs/signer.md
  go.mod
  go.sum
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/opencontainers/go-digest/.mailmap
  vendor/github.com/opencontainers/go-digest/.pullapprove.yml
  vendor/github.com/opencontainers/go-digest/.travis.yml
  vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
  vendor/github.com/opencontainers/go-digest/LICENSE
  vendor/github.com/opencontainers/go-digest/LICENSE.docs
  vendor/github.com/opencontainers/go-digest/MAINTAINERS
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/github.com/opencontainers/go-digest/verifiers.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: size/XXL
