Repository grafeas/kritis, pull requests merged in 2020-03, with the labels that each got.

#477 Remove public key in signer interface
  cmd/kritis/signer/main.go
  pkg/kritis/gcbsigner/signer.go
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/grafeas/grafeas_test.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/review/review.go
  pkg/kritis/secrets/pgpkey.go
  pkg/kritis/signer/signer.go
  pkg/kritis/testutil/metadata_mock.go
Labels: size/M

#478 Add passphrase support for signing key
  cmd/kritis/signer/main.go
Labels: size/XS

#479 Add public key back to signer tool
  cmd/kritis/signer/main.go
  pkg/kritis/secrets/pgpkey.go
Labels: size/M

#480 Update install.md
  docs/install.md
Labels: size/XS

#474 Multiple key types - Create RawAttestation wrapper
  Gopkg.lock
  Gopkg.toml
  integration/attestation.go
  pkg/kritis/container/container.go
  pkg/kritis/container/container_test.go
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/cache_test.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/metadata/metadata_test.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
  pkg/kritis/testutil/metadata_mock.go
  pkg/kritis/util/util.go
  pkg/kritis/util/util_test.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
Labels: kokoro:run

#481 Fix logic for rejecting image.
  pkg/kritis/signer/signer.go
Labels: size/XS

#482 Fix may cause panic when getting metadata client failed
  pkg/kritis/admission/admission.go
Labels: size/XS

#488 Merge RawAttestation Wrapper PR into master
  Gopkg.lock
  Gopkg.toml
  integration/attestation.go
  pkg/kritis/container/container.go
  pkg/kritis/container/container_test.go
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/cache_test.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/metadata/metadata_test.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
  pkg/kritis/testutil/metadata_mock.go
  pkg/kritis/util/util.go
  pkg/kritis/util/util_test.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
Labels: size/XXL

#486 Create PublicKey wrapper for AttestationAuthoritySpec
  docs/resources.md
  docs/standalone/no_attestation.sh
  docs/tutorial.md
  integration/crd.go
  integration/run_test.go
  integration/testdata/generic-attestation-policy/test-attestor-1.yaml
  integration/testdata/generic-attestation-policy/test-attestor-2.yaml
  integration/testdata/keys/attestor-1-secret-key.pgp
  integration/testdata/keys/attestor-2-secret-key.pgp
  pkg/kritis/apis/kritis/v1beta1/attestationauthority.go
  pkg/kritis/apis/kritis/v1beta1/zz_generated.deepcopy.go
  pkg/kritis/container/container.go
  pkg/kritis/gcbsigner/signer_test.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
Labels: size/L
