Repository grafeas/kritis, pull requests merged in 2020-08, with the labels that each got.

#576 Update pkix key parser
  pkg/attestlib/pkix_key.go
  pkg/attestlib/pkix_key_test.go
Labels: size/M

#575 Implement verify pkix
  pkg/attestlib/pkix.go
  pkg/attestlib/pkix_key.go
  pkg/attestlib/pkix_key_test.go
  pkg/attestlib/pkix_test.go
  pkg/attestlib/public_key.go
  pkg/attestlib/verifier.go
  pkg/attestlib/verifier_test.go
Labels: size/L

#569 Add tutorial for Crypto Library
  pkg/attestlib/tutorial.md
Labels: size/L

#573 Add better command line usage for signer tool
  cmd/kritis/signer/main.go
Labels: size/L

#577 Add sample file for signer user guide
  samples/signer/.gcloudignore
  samples/signer/.gitignore
  samples/signer/Dockerfile.bad
  samples/signer/Dockerfile.good
  samples/signer/cloudbuild-bad.yaml.template
  samples/signer/cloudbuild-good.yaml.template
  samples/signer/policy.yaml
Labels: size/L

#582 Doc update
  samples/signer/cloudbuild-bad.yaml
  samples/signer/cloudbuild-good.yaml
Labels: size/S

#580 Add documentation for signer
  docs/signer.md
Labels: size/L
