Repository grafeas/kritis, pull requests merged in 2020-05, with the labels that each got.

#499 Add key lookup to crypto interface
  pkg/kritis/cryptolib/pgp.go
  pkg/kritis/cryptolib/pgp_test.go
  pkg/kritis/cryptolib/verifier.go
  pkg/kritis/cryptolib/verifier_test.go
Labels: size/L

#502 Verify payload contents in crypto library
  pkg/kritis/cryptolib/authenticated_attestation.go
  pkg/kritis/cryptolib/authenticated_attestation_test.go
  pkg/kritis/cryptolib/verifier.go
  pkg/kritis/cryptolib/verifier_test.go
Labels: size/L

#500 Minimal integration of crypto interface into Kritis
  pkg/kritis/review/validating_transport.go
Labels: size/M

#504 Correct the LICENSE text.
  LICENSE
Labels: size/XS

#509 Minor cleanup
  docs/tutorial.md
  pkg/kritis/apis/kritis/v1beta1/attestationauthority.go
Labels: size/XS

#511 [ISSUE-506] Remove base64 encoding/decoding for attestation signatures.
  pkg/kritis/attestation/attestation_test.go
  pkg/kritis/container/container_test.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
  pkg/kritis/testutil/constants.go
Labels: size/M

#498 Fix issues in signer demo
  cmd/kritis/signer/main.go
  pkg/kritis/apis/kritis/v1beta1/vulnzsigningpolicy.go
  samples/signer/cloudbuild-bad.yaml
  samples/signer/cloudbuild-good.yaml
  samples/signer/policy_template.yaml
  samples/signer/setup.sh
  samples/signer/wait-for-analysis.py
Labels: size/M

#510 function for verifying JWT up to (not including) signature verifcation
  pkg/kritis/cryptolib/jwt.go
  pkg/kritis/cryptolib/jwt_test.go
  pkg/kritis/cryptolib/verifier.go
Labels: size/L

#515 [ISSUE-506] Remove unnecessary error check
  pkg/kritis/review/validating_transport.go
Labels: size/XS
