Repository grafeas/kritis, pull requests merged in 2020-06, with the labels that each got.

#517 Add PGP Signing to Cryptolib
  pkg/kritis/cryptolib/pgp.go
  pkg/kritis/cryptolib/pgp_test.go
  pkg/kritis/cryptolib/signer.go
Labels: size/L

#519 Replace RawAttestation with Cryptolib Attestation
  pkg/kritis/cryptolib/attestation.go
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/cache_test.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/metadata/metadata_test.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
  pkg/kritis/testutil/metadata_mock.go
Labels: size/XL

#523 Use EffectiveSeverity instead of Severity in vulnerability details.
  pkg/kritis/metadata/metadata.go
  pkg/kritis/metadata/metadata_test.go
Labels: size/XS

#528 Remove need of service account credentials for signer
  cmd/kritis/signer/main.go
Labels: size/S

#537 Create doc_request.md, an issue template for documentation updates
  .github/ISSUE_TEMPLATE/doc_request.md
  CONTRIBUTING_DOCS.md
Labels: size/M

#524 Add end-to-end test for PGP in Crypto Library
  pkg/kritis/cryptolib/e2etest/pgp_e2e_test.go
Labels: size/L

#538 Add bypass-and-sign mode in signer
  cmd/kritis/signer/main.go
  pkg/kritis/signer/signer.go
Labels: size/M

#518 Add cloud build testing for signer integration.
  integration/signer/Dockerfile.bad
  integration/signer/Dockerfile.good
  integration/signer/cloudbuild.yaml
  integration/signer/policy_template.yaml
  integration/signer/private.key
  integration/signer/public.key
  integration/signer/signer_int.sh
Labels: size/L

#527 Support polling for vulnerability results in signer CLI
  cmd/kritis/signer/main.go
  integration/signer/policy_template.yaml
  integration/signer/signer_int.sh
  integration/signer/tests/test-bypass-and-sign.sh
  integration/signer/tests/test-check-and-sign-bad.sh
  integration/signer/tests/test-check-and-sign-good.sh
  pkg/kritis/metadata/containeranalysis/cache.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/metadata/metadata.go
  pkg/kritis/testutil/metadata_mock.go
  pkg/kritis/util/util.go
Labels: size/L

#543 Remove attestation project and note name from policy spec
  cmd/kritis/signer/main.go
  integration/signer/policy_template.yaml
  integration/signer/signer_int.sh
  integration/signer/tests/test-bypass-and-sign.sh
  integration/signer/tests/test-check-and-sign-bad.sh
  integration/signer/tests/test-check-and-sign-good.sh
  pkg/kritis/apis/kritis/v1beta1/vulnzsigningpolicy.go
  pkg/kritis/util/util.go
Labels: size/L

#536 Create release.md issue template
  .github/ISSUE_TEMPLATE/release.md
  RELEASING.md
Labels: size/S

#532 Validate public key ID in NewPublicKey
  pkg/kritis/cryptolib/e2etest/pgp_e2e_test.go
  pkg/kritis/cryptolib/verifier.go
  pkg/kritis/cryptolib/verifier_test.go
  pkg/kritis/review/validating_transport.go
  pkg/kritis/review/validating_transport_test.go
Labels: size/L

#533 Integrate Cryptolib Signer into Kritis
  docs/standalone/create_attestation.go
  pkg/kritis/metadata/containeranalysis/containeranalysis.go
  pkg/kritis/metadata/grafeas/grafeas.go
  pkg/kritis/review/review_test.go
  pkg/kritis/review/validating_transport_test.go
  pkg/kritis/util/util.go
Labels: size/L

#534 Delete unused attestation file
  pkg/kritis/attestation/attestation.go
  pkg/kritis/attestation/attestation_test.go
Labels: size/L

#542 Update vulnerability signing policy spec
  cmd/kritis/signer/main.go
  integration/signer/policy_template.yaml
  pkg/kritis/apis/kritis/v1beta1/vulnzsigningpolicy.go
  pkg/kritis/apis/kritis/v1beta1/zz_generated.deepcopy.go
  pkg/kritis/crd/vulnzsigningpolicy/violation.go
  pkg/kritis/crd/vulnzsigningpolicy/vulnzsigningpolicy.go
Labels: size/M

#544 Support check only mode
  cmd/kritis/signer/main.go
  integration/signer/signer_int.sh
  integration/signer/tests/test-check-only-bad.sh
  integration/signer/tests/test-check-only-good.sh
  pkg/kritis/signer/signer.go
Labels: size/L

#546 Set key id in kms signer
  pkg/kritis/signer/cloud_kms.go
Labels: size/XS

#547 Update command line parameters and policy in signer demo
  samples/signer/cloudbuild-bad.yaml
  samples/signer/cloudbuild-good.yaml
  samples/signer/policy_template.yaml
Labels: size/S

#548 Add cloud builder for signer image.
  .dockerignore
  deploy/kritis-signer/Dockerfile
  deploy/kritis-signer/cloudbuild.yaml
  integration/signer/cloudbuild.yaml
  samples/signer/setup.sh
Labels: size/M

#545 Reduce demo scope
  samples/signer/cloudbuild-bad.yaml
  samples/signer/cloudbuild-good.yaml
  samples/signer/gen-keys.sh
  samples/signer/setup.sh
  samples/signer/signtest.sh
  samples/signer/wait-for-analysis.py
Labels: size/L

#551 Pinpoint debian versions in Dockerfile
  integration/signer/Dockerfile.bad
  integration/signer/Dockerfile.good
  samples/signer/Dockerfile.bad
  samples/signer/Dockerfile.good
Labels: size/S

#553 Update setup.sh
  samples/policy-check/setup.sh
Labels: size/XS

#550 Move PublicKey into its own file
  pkg/kritis/cryptolib/public_key.go
  pkg/kritis/cryptolib/verifier.go
Labels: size/L
